### ISSUE TITLE
The craft guide search field prevents closing inventory.

### ISSUE THREAD

**Issue by Crabman77** [minetest-mods/unified_inventory#205] opened 2022-06-26 16:39 UTC
Hi,
The search field takes focus when you open the inventory and you have to click on the formspec to be able to close the inventory, it's annoying and break gameplay.

Can you add a simple button to hide/show the guide (or the search field), the guide is not permanently useful, it can be hidden 90% of the time and the server uses less resources each time you open the inventory.

We had done it on our fork for our old server, but on the other public servers which have this mod it's painful.
https://github.com/MinetestForFun/server-minetestforfun/commit/d676da66a7f9e26bbe576c2f493155cf76a03310

**Comment by SmallJoker** [comment] 2022-06-26 20:38
Cannot reproduce on MInetest 5.5.0-dev. The field is selected but ESC does exit the formspec as expected. Please test again with a newer Minetest version.

**Comment by Crabman77** [comment] 2022-06-27 11:58
Yes ESC works, but it's not practical, it's the key binded to open/close the inventory that I'm talking about.

But this morning I found a way around the problem, it's not practical but better than the ESC key or always having to click on the formspec to take focus.

If you select the craft guide and a craft, it prevents the text field from taking focus and the inventory key works as it should.

https://www.youtube.com/watch?v=k9fXv1R64fU

You can close the issue if for you it is not an annoying bug, I will do with the craft guide method if there is no good solution to not have the text field without deforming the mod.

**Comment by SmallJoker** [comment] 2022-08-06 06:59
I'd suggest to close the inventory like any regular formspec: either by double-clicking outside the area or by pressing ESC. Closing the inventory with this hotkey is not explicitly documented (minetest.conf.example) and does not work in all cases (as reported in this issue).

I don't think this behaviour needs a change. Feel free to customize it on your side if it somehow breaks your workflow.

**Closed by SmallJoker** 2022-08-06 06:59 UTC

**Comment by SmallJoker** [comment] 2023-04-05 18:36
It seems that this was already raised in #31 but closed the same way I did. I do see that it's not practical to have the search field focused in this case, but in the other turn there' might be people relying on this behaviour (please correct me if I'm wrong about this).

If you have a solution which is generally accepted, please let me know so that Unified Inventory can be made easier to use for more people.
